#!/bin/env ruby
# encoding: utf-8

REGIONS = ["Koç Üniversitesi",
"Adalar",
"Arnavutköy",
"Ataşehir",
"Avcılar",
"Bahçelievler",
"Bakırköy",
"Bayrampaşa",
"Bağcılar",
"Başakşehir",
"Beykoz",
"Beylikdüzü",
"Beyoğlu",
"Beşiktaş",
"Büyükçekmece",
"Çatalca",
"Çekmeköy",
"Esenler",
"Esenyurt",
"Eyüp",
"Fatih",
"Gaziosmanpaşa",
"Güngören",
"Kadıköy",
"Kartal",
"Kağıthane",
"Küçükçekmece",
"Maltepe",
"Pendik",
"Sancaktepe",
"Sarıyer",
"Silivri",
"Sultanbeyli",
"Sultangazi",
"Şile",
"Şişli",
"Ümraniye",
"Üsküdar",
"Tuzla",
"Zeytinburnu"]

SAMPLE_FAVORITES = ["Kanyon, Istanbul", "Istinye Park, Istanbul", "Koc Universitesi, Istanbul", "Taksim, Istanbul", "Besiktas KafePi, Istanbul", "Anjelique, Istanbul", "Garipce, Istanbul", "Benzin Cafe, Kadikoy, Istanbul"]